language: node_js
node_js:
- 11.1.60
cache: yarn


install:
    -yarn ci
script:
    -yarn test
    -yarn run build

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
